### ISSUE TITLE
Using Connection String URI Format

### ISSUE THREAD

**Issue by daknightproductions** [cobrateam/flask-mongoalchemy#40]
Hi,

Is that possible to add the Standard Connection String Format (http://docs.mongodb.org/manual/reference/connection-string/#standard-connection-string-format)

I am writing this issue at http://stackoverflow.com/questions/29030257/flask-mongoalchemy-with-multi-hosts-urls

Cheers

**Comment by fsouza** [comment]
Hi @daknightproductions, currently it is not, but it's quite easy to do so. Do you wanna send a patch?

Currently, the code builds the URI from the configuration parameters [1]. We can add a new configuration parameter for the URI, and then the code won't need to build it.

[1] https://github.com/cobrateam/flask-mongoalchemy/blob/master/flask_mongoalchemy/__init__.py#L22:L50

**Comment by daknightproductions** [comment]
Hey there,

Well of course it's easy to hack it but i think it's nice to let other
people to have it too, especially if we use pip install. If you have time
in the future, please add 1 extra param which take a whole uri and just
return it if it is not empty....or something better :)


Cheers



Många varma kramar
Oai Gudmundsson

<http://daknight.se>
Web Dev 3.0
Oai Gudmundsson
+46812061700

**Comment by fsouza** [comment]
Sure, I will do it later today. Thanks for reporting it!

**Comment by fsouza** [comment]
It's fixed and released, please upgrade to the version 0.7.1.

Thanks for reporting!

**Comment by daknightproductions** [comment]
Thank you very much! :)

Många varma kramar
Oai Gudmundsson

<http://daknight.se>
Web Dev 3.0
Oai Gudmundsson
+46812061700

**Comment by lysdexia** [comment]
Is this still working? I'm having the same problem in version 0.7.2
